attuladzan_markdown_editor:
    editor:
        allow_html: false
        sticky_toolbar: true
        autofocus: false
        lang: en
    plugins:
        mermaid: false
        latex: false
        html: false
